# Generated by Django 4.2.13 on 2024-06-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Giza', 'Giza'), ('Shubra El-Kheima', 'Shubra El-Kheima'), ('Port Said', 'Port Said'), ('Suez', 'Suez'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan'), ('Damietta', 'Damietta'), ('Faiyum', 'Faiyum'), ('Minya', 'Minya'), ('Qena', 'Qena'), ('Qalyoubia', 'Qalyoubia'), ('Sohag', 'Sohag'), ('Hurghada', 'Hurghada'), ('Ismailia', 'Ismailia'), ('Mansoura', 'Mansoura'), ('Tanta', 'Tanta'), ('Zagazig', 'Zagazig'), ('Asyut', 'Asyut'), ('Beni Suef', 'Beni Suef'), ('Banha', 'Banha'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Mahalla', 'Mahalla'), ('Damanhur', 'Damanhur'), ('El-Minya', 'El-Minya'), ('El Arish', 'El Arish'), ('Ras Gharib', 'Ras Gharib'), ('Port Safaga', 'Port Safaga')], max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
