CAR_BRANDS = (
    ('audi', 'Audi'),
    ('bmw', 'BMW'),
    ('ford', 'Ford'),
    ('mercedes', 'Mercedes'),
    ('volkswagen', 'Volkswagen'),
    ('volvo', 'Volvo'),
    ('renault', 'Renault'),
    ('skoda', 'Skoda'),
    ('citroen', 'Citroen'),
    ('peugeot', 'Peugeot'),
    ('fiat', 'Fiat'),
    ('nissan', 'Nissan'),
    ('toyota', 'Toyota'),
    ('mazda', 'Mazda'),
    ('subaru', 'Subaru'),
    ('honda', 'Honda'),
    ('hyundai', 'Hyundai'),
    ('lexus', 'Lexus'),
    ('jaguar', 'Jaguar'),
    ('porsche', 'Porsche'),
    ('bentley', 'Bentley'),
    ('dodge', 'Dodge'),
    ('kia', 'Kia'),
    ('mitsubishi', 'Mitsubishi'),
    ('suzuki', 'Suzuki'),
    ('Alfa-Romeo', 'Alfa-Romeo'),
    ('Cadillac', 'Cadillac'),
    ('Chevrolet', 'Chevrolet'),
    ('Chrysler', 'Chrysler'),
    ('lotus', 'Lotus'),
    ('mg', 'MG'),
    ('lamborghini','Lamborghini'),
    ('maserati','Maserati'),
    ('seat','Seat'),
    ('cupra', 'Cupra'),
    ('ferrari', 'Ferrari'),
    ('tesla', 'Tesla'),
    ('BYD', 'BYD'),
    ('ds','DS'),
    ('haval','Haval'),
    ('Zotye', 'Zotye'),
    ('jeep', 'Jeep'),
    ('opel', 'Opel'),
    ('land Rover', 'Land Rover'),
    ('Range Rover', 'Range Rover'),
    ('lexus', 'Lexus'),
    ('mazda', 'Mazda'),
    ('cherry', 'Cherry'),
    ('rolls royce', 'Rolls Royce'),
    ('mini cooper', 'Mini Cooper'),
    ('aston martin', 'Aston Martin'),
    ('infiniti', 'Infiniti'),
    ('mc-laren', 'Mc-Laren'),
    ('maybach', 'Maybach'),
    ('Brabus', 'Brabus'),
    ('alpina', 'Alpina'),
    ('mansory', 'Mansory'),
)

TRANSMISSIONS_OPTIONS = (
    ('automatic', 'Automatic'),   
    ('manual', 'Manual'),
)   