# Generated by Django 4.2.13 on 2024-06-28 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_listing_brands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='brands',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='transmission',
            new_name='transmisson',
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
